#!/bin/sh

# SETUP: put this file and python script in a directory (i.e. Documents/gitScripts)
# Add a line with this directory to PATH (.bash_profile for Macs):
# For example, add this: export PATH="/Users/Nancy/Documents/gitScripts:$PATH"
# In directory, set permissions to execute by calling "chmod 555"
# TO CALL: git talk "commit message goes here"

commitMessage=$1
test -z "$commitMessage" && echo "ERROR: Please provide a commit message." 1>&2 && exit 1

# Run python script for Quicktime - get filepath
echo "Running QuicktimeAutomation.py script to start QuickTime screen recording..."
dir=$(dirname $0)
filePath=$(python $(dirname "$dir")/QuicktimeAutomation.py)
testPath=/Users/Nancy/Documents/test.mov
echo "FILE PATH RETURNED:" $testPath

# Run python script for YouTube upload
echo "Running upload.py script to upload to YouTube" 
$(python $dir/../upload.py --file $testPath --title $commitMessage)
# echo $youtubeLink

# Git commit including YouTube link
# newCommitMessage="$commitMessage \nYouTube link: $youtubeLink"
echo "Running git commit with message:\n" $newCommitMessage
# git commit -m "$newCommitMessage"
